defaults:
  - data_guitar
  - _self_

instrument:
  name: guitar_gaps

sampler_options:
  realism_v1:
    stats_path: ${paths.analysis_dir}/stats/midi_sampler/GAPS_sampler.json

  realism_v2:
    stats_path: ${paths.analysis_dir}/stats/midi_sampler/GAPS_sampler.json

  mixed_v2:
    components:
      realism:
        stats_path: ${paths.analysis_dir}/stats/midi_sampler/GAPS_sampler.json
